"use client";

import { useMemo, useState } from "react";
import type { Questionnaire, TriageResult } from "./types";
import { Badge, Button, Card, CardBody, CardHeader, Divider, TextArea } from "./ui";

function triageTone(level: TriageResult["triage_level"]) {
  switch (level) {
    case "emergency":
      return { tone: "red" as const, label: "Emergency" };
    case "urgent":
      return { tone: "amber" as const, label: "Urgent" };
    case "non_urgent":
      return { tone: "slate" as const, label: "Non-urgent" };
    case "self_care":
      return { tone: "green" as const, label: "Self-care" };
  }
}

export default function ResultsPanel({
  q,
  result,
  onReset
}: {
  q: Questionnaire;
  result: TriageResult;
  onReset: () => void;
}) {
  const [providerEmail, setProviderEmail] = useState("");
  const [copied, setCopied] = useState(false);

  const tone = triageTone(result.triage_level);

  const summaryText = useMemo(() => {
    const lines: string[] = [];
    lines.push("Symptom Triage Summary (Generated by TriageNow)");
    lines.push("");
    lines.push(`Symptoms: ${q.symptoms.join(", ") || "—"}`);
    lines.push(`Age: ${q.ageYears ?? "—"}`);
    lines.push(`Sex: ${q.sex}`);
    lines.push(`Duration: ${q.durationValue} ${q.duration}`);
    lines.push(`Severity (1-5): ${q.severity}`);
    lines.push(`Fever: ${q.fever}`);
    lines.push(`Pregnancy: ${q.pregnancy}`);
    lines.push("");
    lines.push(`Triage level: ${result.triage_level.toUpperCase()}`);
    lines.push(`Summary: ${result.summary}`);
    lines.push("");
    lines.push("Rationale:");
    for (const r of result.rationale) lines.push(`- ${r}`);
    lines.push("");
    lines.push("Possible conditions:");
    for (const c of result.possible_conditions) lines.push(`- ${c.name} (${c.likelihood}): ${c.why_it_fits}`);
    lines.push("");
    lines.push("Recommended actions:");
    lines.push("Self-care:");
    for (const s of result.self_care) lines.push(`- ${s}`);
    lines.push("Pharmacy:");
    for (const s of result.pharmacy_advice) lines.push(`- ${s}`);
    lines.push("See a doctor:");
    for (const s of result.see_doctor) lines.push(`- ${s}`);
    lines.push("Emergency:");
    for (const s of result.emergency_actions) lines.push(`- ${s}`);
    lines.push("");
    lines.push("Disclaimer:");
    lines.push(result.disclaimer);
    return lines.join("\n");
  }, [q, result]);

  async function copySummary() {
    await navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const mailto = providerEmail
    ? `mailto:${encodeURIComponent(providerEmail)}?subject=${encodeURIComponent("Symptom Triage Summary")}&body=${encodeURIComponent(summaryText)}`
    : null;

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader title="Your Result" subtitle="Use this as guidance; it is not a diagnosis." />
        <CardBody>
          <div className="flex flex-wrap items-center gap-3">
            <Badge tone={tone.tone}>{tone.label}</Badge>
            <div className="text-sm text-slate-700">{result.summary}</div>
          </div>

          <Divider />

          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <h4 className="text-sm font-semibold">Why this recommendation</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                {result.rationale.map((r, i) => (
                  <li key={i}>{r}</li>
                ))}
              </ul>
            </div>

            <div className="space-y-2">
              <h4 className="text-sm font-semibold">Red flags to watch</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                {result.red_flags_to_watch.map((r, i) => (
                  <li key={i}>{r}</li>
                ))}
              </ul>
            </div>
          </div>

          <Divider />

          <div className="space-y-2">
            <h4 className="text-sm font-semibold">Possible conditions (not a diagnosis)</h4>
            <div className="space-y-2">
              {result.possible_conditions.map((c, i) => (
                <div key={i} className="rounded-xl border border-slate-200 p-3">
                  <div className="flex items-center justify-between gap-3">
                    <div className="font-medium">{c.name}</div>
                    <Badge>{c.likelihood}</Badge>
                  </div>
                  <p className="mt-1 text-sm text-slate-700">{c.why_it_fits}</p>
                </div>
              ))}
            </div>
          </div>

          <Divider />

          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <h4 className="text-sm font-semibold">Self-care</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                {result.self_care.map((x, i) => (
                  <li key={i}>{x}</li>
                ))}
              </ul>

              <h4 className="mt-4 text-sm font-semibold">Pharmacy</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                {result.pharmacy_advice.map((x, i) => (
                  <li key={i}>{x}</li>
                ))}
              </ul>
            </div>

            <div className="space-y-2">
              <h4 className="text-sm font-semibold">See a doctor</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                {result.see_doctor.map((x, i) => (
                  <li key={i}>{x}</li>
                ))}
              </ul>

              <h4 className="mt-4 text-sm font-semibold">Emergency</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                {result.emergency_actions.map((x, i) => (
                  <li key={i}>{x}</li>
                ))}
              </ul>
            </div>
          </div>

          <Divider />

          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <h4 className="text-sm font-semibold">Share a summary (optional)</h4>
            <p className="mt-1 text-xs text-slate-600">
              You stay anonymous unless you choose to share. Enter a provider email to open your email client, or copy the summary.
            </p>

            <div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-3">
              <div className="md:col-span-1">
                <label className="text-xs font-medium text-slate-700">Provider email (optional)</label>
                <input
                  className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-slate-200"
                  value={providerEmail}
                  onChange={(e) => setProviderEmail(e.target.value)}
                  placeholder="clinic@example.com"
                />
              </div>
              <div className="md:col-span-2">
                <label className="text-xs font-medium text-slate-700">Summary</label>
                <TextArea className="mt-2 h-32" value={summaryText} readOnly />
              </div>
            </div>

            <div className="mt-3 flex flex-wrap items-center gap-2">
              <Button onClick={copySummary} variant="secondary">
                {copied ? "Copied" : "Copy summary"}
              </Button>
              {mailto ? (
                <a
                  className="inline-flex items-center justify-center rounded-xl px-4 py-2 text-sm font-medium bg-slate-900 text-white hover:bg-slate-800"
                  href={mailto}
                >
                  Email summary
                </a>
              ) : (
                <span className="text-xs text-slate-500">Add an email to enable “Email summary”.</span>
              )}
            </div>
          </div>

          <Divider />

          <div className="flex items-center justify-between gap-3">
            <p className="text-xs text-slate-600">{result.disclaimer}</p>
            <Button onClick={onReset} variant="secondary">
              Start over
            </Button>
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
